# Function to generate a script for Pi-Star that adds MASTER instances and generated passphrases to DMR_Hosts.txt.

def gen_script(dmr_id, svr_lst):
    auth_contents = ''
    for i in svr_lst:
        auth_contents = auth_contents + str(i[0]) + '''\t\t\t''' + str(dmr_id) + '''\t''' + i[1] + '''\t\t\t''' + i[2] + '''\t\t''' + str(i[3]) + '\n'
    output = '''
# Generated by HBNet \n
''' + auth_contents + '''
'''
    return output
